//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class recruitment
    {
        public int IdRec { get; set; }
        public string Code { get; set; }
        public string Position { get; set; }
        public string Salary { get; set; }
        public string Place { get; set; }
        public string Expiry { get; set; }
        public string Url { get; set; }
        public bool Saved { get; set; }
        public System.DateTime Rodate { get; set; }
    }
}
