//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuyenDung
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NGANH_NGHE_NGUON
    {
        public DM_NGANH_NGHE_NGUON()
        {
            this.TUYEN_DUNG = new HashSet<TUYEN_DUNG>();
        }
    
        public int ID_NGANH_NGHE_NGUON { get; set; }
        public int MA_NGANH_NGHE { get; set; }
        public string TEN_NGANH_NGHE { get; set; }
        public int ID_NGUON { get; set; }
        public Nullable<int> ID_NGANH_NGHE { get; set; }
    
        public virtual DM_NGANH_NGHE DM_NGANH_NGHE { get; set; }
        public virtual NGUON NGUON { get; set; }
        public virtual ICollection<TUYEN_DUNG> TUYEN_DUNG { get; set; }
    }
}
