//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuyenDung
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUON
    {
        public NGUON()
        {
            this.DM_NGANH_NGHE_NGUON = new HashSet<DM_NGANH_NGHE_NGUON>();
            this.DM_TINH_NGUON = new HashSet<DM_TINH_NGUON>();
            this.TUYEN_DUNG = new HashSet<TUYEN_DUNG>();
        }
    
        public int ID_NGUON { get; set; }
        public string TEN_NGUON { get; set; }
    
        public virtual ICollection<DM_NGANH_NGHE_NGUON> DM_NGANH_NGHE_NGUON { get; set; }
        public virtual ICollection<DM_TINH_NGUON> DM_TINH_NGUON { get; set; }
        public virtual ICollection<TUYEN_DUNG> TUYEN_DUNG { get; set; }
    }
}
